services:

  redis-master:
    container_name: confiacim-api-redis-redis-master
    image: redis:7.2-alpine
    command: redis-server

    ports:
      - 6379:6379

  sentinel:
    container_name: confiacim-api-redis-sentinel
    image: redis:7.2-alpine
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./docker/sentinel/sentinel.conf:/etc/sentinel.conf"

    depends_on:
      - redis-master

    ports:
      - 26379:26379


  database:
    container_name: confiacim-api-db
    build:
      context: docker/postgres
    restart: 'no'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DBS=confiacim_api, confiacim_api_test
    ports:
      - 5432:5432

  api:
    container_name: confiacim-api
    build:
      dockerfile: ./Dockerfile.dev
    image: confiacim_api:dev
    volumes:
      - ./:/home/app/
    restart: 'no'
    stdin_open: true
    tty: true
    environment:
      PYTHONBREAKPOINT: ipdb.set_trace
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: database
      DB_NAME: confiacim_api
      SENTINEL_MASTER_NAME: mymaster
      SENTINEL_HOST: sentinel
    ports:
      - 8000:8000
    depends_on:
      - database
      - sentinel

  worker_1:
    image: confiacim_api:dev
    command: watchfiles --filter python 'celery -A confiacim_api.celery worker  -n 'worker@1' --concurrency=2 -l INFO'
    depends_on:
      - sentinel
    volumes:
      - ./:/home/app/
    environment:
      WATCHFILES_FORCE_POLLING: true
      DB_PASSWORD: password
      DB_HOST: database
      DB_NAME: confiacim_api
      SENTINEL_MASTER_NAME: mymaster
      SENTINEL_HOST: sentinel

  worker_2:
    image: confiacim_api:dev
    command: watchfiles --filter python 'celery -A confiacim_api.celery worker  -n 'worker@2' --concurrency=2 -l INFO'
    depends_on:
      - sentinel
    volumes:
      - ./:/home/app/
    environment:
      WATCHFILES_FORCE_POLLING: true
      DB_PASSWORD: password
      DB_HOST: database
      DB_NAME: confiacim_api
      SENTINEL_MASTER_NAME: mymaster
      SENTINEL_HOST: sentinel

  flower:
    image: confiacim_api:dev
    volumes:
      - ./:/home/app/
    environment:
      DB_PASSWORD: password
      DB_HOST: database
      DB_NAME: confiacim_api
      SENTINEL_MASTER_NAME: mymaster
      SENTINEL_HOST: sentinel

    command: celery -A confiacim_api.celery --broker=sentinel://sentinel:26379/0 flower --port=5555 --url-prefix=flower

    ports:
      - 5555:5555

volumes:
  pg_data:
