services:

  nginx:
    container_name: nginx-backend
    restart: 'no'
    build:
      context: docker/nginx/
    networks:
      - internal_nw
    ports:
      - 80:80
    depends_on:
      - api

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '500M'

  redis-master:
    container_name: confiacim-api-redis-redis-master
    image: redis:7.2-alpine
    command: redis-server

    networks:
      - internal_nw

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '250M'

  sentinel:
    container_name: confiacim-api-redis-sentinel
    image: redis:7.2-alpine
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./docker/sentinel/sentinel.conf:/etc/sentinel.conf"

    depends_on:
      - redis-master

    networks:
      - internal_nw

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '250M'

  database:
    container_name: confiacim-api-db
    build:
      context: docker/postgres
    restart: 'no'
    networks:
      - internal_nw
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DBS=confiacim_api, confiacim_api_test

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'

  api:
    container_name: confiacim-api
    build:
      dockerfile: ./Dockerfile.prod
    image: confiacim_api:latest
    command: "gunicorn confiacim_api.app:app --workers 3 --log-level info --access-logfile '-' --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    restart: 'no'
    networks:
      - internal_nw

    environment:
      CONFIACIM_API_DB_USER: user
      CONFIACIM_API_DB_PASSWORD: password
      CONFIACIM_API_DB_HOST: database
      CONFIACIM_API_DB_NAME: confiacim_api
      CONFIACIM_API_SENTINEL_MASTER_NAME: mymaster
      CONFIACIM_API_SENTINEL_HOST: sentinel
      CONFIACIM_API_JWT_SECRET_KEY: Chave Secreta JWT
      CONFIACIM_CORE_EXEC_TENCIM_MODE: SEQUENTIAL
      ACCESS_TOKEN_EXPIRE_MINUTES: 864000

    depends_on:
      - database
      - sentinel

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '500M'

  worker:
    image: confiacim_api:latest
    command: celery -A confiacim_api.celery worker  --concurrency=1 -l INFO
    restart: 'no'
    networks:
      - internal_nw
    depends_on:
      - sentinel

    environment:
      CONFIACIM_API_DB_USER: user
      CONFIACIM_API_DB_PASSWORD: password
      CONFIACIM_API_DB_HOST: database
      CONFIACIM_API_DB_NAME: confiacim_api
      CONFIACIM_API_SENTINEL_MASTER_NAME: mymaster
      CONFIACIM_API_SENTINEL_HOST: sentinel
      CONFIACIM_API_JWT_SECRET_KEY: Chave Secreta JWT
      CONFIACIM_CORE_EXEC_TENCIM_MODE: SEQUENTIAL
      ACCESS_TOKEN_EXPIRE_MINUTES: 864000

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '500M'

  flower:
    image: confiacim_api:latest
    restart: 'no'
    environment:
      CONFIACIM_API_DB_USER: user
      CONFIACIM_API_DB_PASSWORD: password
      CONFIACIM_API_DB_HOST: database
      CONFIACIM_API_DB_NAME: confiacim_api
      CONFIACIM_API_SENTINEL_MASTER_NAME: mymaster
      CONFIACIM_API_SENTINEL_HOST: sentinel
      CONFIACIM_API_JWT_SECRET_KEY: Chave Secreta JWT

    networks:
      - internal_nw
    command: celery -A confiacim_api.celery --broker=sentinel://sentinel:26379/0 flower --port=5555 --url-prefix=flower
    depends_on:
      - sentinel

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '200M'

volumes:
  pg_data:

networks:
  internal_nw:
