services:

  nginx:
    container_name: nginx-backend
    restart: 'no'
    build:
      context: docker/nginx/
    networks:
      - internal_nw
    ports:
      - 80:80
    depends_on:
      - api

  redis-master:
    container_name: confiacim-api-redis-redis-master
    image: redis:7.2-alpine
    command: redis-server

    networks:
      - internal_nw

  sentinel:
    container_name: confiacim-api-redis-sentinel
    image: redis:7.2-alpine
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./docker/sentinel/sentinel.conf:/etc/sentinel.conf"

    depends_on:
      - redis-master

    networks:
      - internal_nw

  database:
    container_name: confiacim-api-db
    build:
      context: docker/postgres
    restart: 'no'
    networks:
      - internal_nw
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DBS=confiacim_api, confiacim_api_test

  api:
    container_name: confiacim-api
    build:
      dockerfile: ./Dockerfile.prod
    image: confiacim_api:latest
    command: "gunicorn confiacim_api.app:app --workers 3 --log-level info --access-logfile '-' --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    restart: 'no'
    networks:
      - internal_nw

    environment:
      CONFIACIM_API_DB_USER: user
      CONFIACIM_API_DB_PASSWORD: password
      CONFIACIM_API_DB_HOST: database
      CONFIACIM_API_DB_NAME: confiacim_api
      CONFIACIM_API_SENTINEL_MASTER_NAME: mymaster
      CONFIACIM_API_SENTINEL_HOST: sentinel
      CONFIACIM_API_JWT_SECRET_KEY: Chave Secreta JWT

    depends_on:
      - database
      - sentinel

  worker_1:
    image: confiacim_api:latest
    command: celery -A confiacim_api.celery worker  -n 'worker@1' --concurrency=2 -l INFO
    restart: 'no'
    networks:
      - internal_nw
    depends_on:
      - sentinel

    environment:
      CONFIACIM_API_DB_USER: user
      CONFIACIM_API_DB_PASSWORD: password
      CONFIACIM_API_DB_HOST: database
      CONFIACIM_API_DB_NAME: confiacim_api
      CONFIACIM_API_SENTINEL_MASTER_NAME: mymaster
      CONFIACIM_API_SENTINEL_HOST: sentinel
      CONFIACIM_API_JWT_SECRET_KEY: Chave Secreta JWT

  flower:
    image: confiacim_api:latest
    restart: 'no'
    environment:
      CONFIACIM_API_DB_USER: user
      CONFIACIM_API_DB_PASSWORD: password
      CONFIACIM_API_DB_HOST: database
      CONFIACIM_API_DB_NAME: confiacim_api
      CONFIACIM_API_SENTINEL_MASTER_NAME: mymaster
      CONFIACIM_API_SENTINEL_HOST: sentinel
      CONFIACIM_API_JWT_SECRET_KEY: Chave Secreta JWT

    networks:
      - internal_nw
    command: celery -A confiacim_api.celery --broker=sentinel://sentinel:26379/0 flower --port=5555 --url-prefix=flower
    depends_on:
      - sentinel

volumes:
  pg_data:

networks:
  internal_nw:
