version: "3.8"

services:

  database:
    container_name: confiacim-api-db
    build:
      context: postgres
    restart: 'no'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=confiacim_api_password
      - POSTGRES_USER=confiacim_api_user
      - POSTGRES_DBS=confiacim_api, confiacim_api_test
    ports:
      - 5432:5432

  api:
    container_name: confiacim-api
    build:
      dockerfile: ./Dockerfile.dev
    image: confiacim_api:dev
    volumes:
      - ./:/home/app/
    restart: 'no'
    stdin_open: true
    tty: true
    environment:
      PYTHONBREAKPOINT: ipdb.set_trace
      DATABASE_URL: postgresql://confiacim_api_user:confiacim_api_password@database:5432/confiacim_api
      CELERY_BROKER_URL: redis://broker:6379
      CELERY_RESULT_BACKEND: redis://broker:6379
    ports:
      - 8000:8000
    depends_on:
      - database
      - broker

  broker:
    container_name: confiacim-api-broker
    image: redis:7.2-alpine

    ports:
      - 6379:6379

  worker_1:
    image: confiacim_api:dev
    command: watchfiles --filter python 'celery -A confiacim_api.celery worker  -n 'worker@1' --concurrency=2 -l INFO'
    depends_on:
      - broker
    volumes:
      - ./:/home/app/
    environment:
      WATCHFILES_FORCE_POLLING: true
      DATABASE_URL: postgresql://confiacim_api_user:confiacim_api_password@database:5432/confiacim_api
      CELERY_BROKER_URL: redis://broker:6379
      CELERY_RESULT_BACKEND: redis://broker:6379

  worker_2:
    image: confiacim_api:dev
    command: watchfiles --filter python 'celery -A confiacim_api.celery worker  -n 'worker@2' --concurrency=2 -l INFO'
    depends_on:
      - broker
    volumes:
      - ./:/home/app/
    environment:
      WATCHFILES_FORCE_POLLING: true
      DATABASE_URL: postgresql://confiacim_api_user:confiacim_api_password@database:5432/confiacim_api
      CELERY_BROKER_URL: redis://broker:6379
      CELERY_RESULT_BACKEND: redis://broker:6379

  flower:
    image: confiacim_api:dev
    command: celery --broker=redis://broker:6379/0 flower --port=5555

    ports:
      - 5555:5555

volumes:
  pg_data:
