services:

  redis-master:
    container_name: confiacim-api-redis-redis-master
    image: redis:7.2-alpine
    command: redis-server

    networks:
      - internal_nw

  sentinel:
    container_name: confiacim-api-redis-sentinel
    image: redis:7.2-alpine
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./docker/sentinel/sentinel.conf:/etc/sentinel.conf"

    depends_on:
      - redis-master

    networks:
      - internal_nw

  database:
    container_name: confiacim-api-db
    build:
      context: docker/postgres
    restart: 'no'
    networks:
      - internal_nw
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DBS=confiacim_api, confiacim_api_test

  api:
    container_name: confiacim-api
    build:
      dockerfile: ./Dockerfile.prod
    image: confiacim_api:latest
    command: "gunicorn confiacim_api.app:app --workers 2 --log-level info --access-logfile '-' --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    restart: 'no'
    networks:
      - internal_nw
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@database:5432/confiacim_api
      CELERY_BROKER_URL: sentinel://sentinel:26379
      CELERY_RESULT_BACKEND: sentinel://sentinel:26379
      SENTINEL_MASTER_NAME: mymaster
    depends_on:
      - database
      - sentinel

  worker_1:
    image: confiacim_api:latest
    command: celery -A confiacim_api.celery worker  -n 'worker@1' --concurrency=2 -l INFO
    restart: 'no'
    networks:
      - internal_nw
    depends_on:
      - sentinel

    environment:
      DATABASE_URL: postgresql+psycopg://user:password@database:5432/confiacim_api
      CELERY_BROKER_URL: sentinel://sentinel:26379
      CELERY_RESULT_BACKEND: sentinel://sentinel:26379
      SENTINEL_MASTER_NAME: mymaster

  worker_2:
    image: confiacim_api:latest
    command: celery -A confiacim_api.celery worker  -n 'worker@2' --concurrency=2 -l INFO
    restart: 'no'
    networks:
      - internal_nw
    depends_on:
      - sentinel

    environment:
      DATABASE_URL: postgresql+psycopg://user:password@database:5432/confiacim_api
      CELERY_BROKER_URL: sentinel://sentinel:26379
      CELERY_RESULT_BACKEND: sentinel://sentinel:26379
      SENTINEL_MASTER_NAME: mymaster

  flower:
    image: confiacim_api:latest
    restart: 'no'
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@database:5432/confiacim_api
      CELERY_BROKER_URL: sentinel://sentinel:26379
      CELERY_RESULT_BACKEND: sentinel://sentinel:26379
      SENTINEL_MASTER_NAME: mymaster
    networks:
      - internal_nw
    command: celery -A confiacim_api.celery --broker=sentinel://sentinel:26379/0 flower --port=5555 --url-prefix=flower
    depends_on:
      - sentinel

volumes:
  pg_data:

networks:
  internal_nw:
    name: "confiacim_internal_nw"
