services:

  broker:
    container_name: confiacim-api-broker
    image: redis:7.2-alpine
    networks:
      - internal_nw

  database:
    container_name: confiacim-api-db
    build:
      context: postgres
    restart: 'no'
    networks:
      - internal_nw
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DBS=confiacim_api, confiacim_api_test

  api:
    container_name: confiacim-api
    build:
      dockerfile: ./Dockerfile.prod
    image: confiacim_api:latest
    command: "gunicorn confiacim_api.app:app --workers 2 --log-level info --access-logfile '-' --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    restart: 'no'
    networks:
      - internal_nw
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@database:5432/confiacim_api
      CELERY_BROKER_URL: redis://broker:6379
      CELERY_RESULT_BACKEND: redis://broker:6379
    depends_on:
      - database
      - broker

  worker_1:
    image: confiacim_api:latest
    command: celery -A confiacim_api.celery worker  -n 'worker@1' --concurrency=2 -l INFO
    restart: 'no'
    networks:
      - internal_nw
    depends_on:
      - broker

    environment:
      DATABASE_URL: postgresql+psycopg://user:password@database:5432/confiacim_api
      CELERY_BROKER_URL: redis://broker:6379
      CELERY_RESULT_BACKEND: redis://broker:6379

  worker_2:
    image: confiacim_api:latest
    command: celery -A confiacim_api.celery worker  -n 'worker@2' --concurrency=2 -l INFO
    restart: 'no'
    networks:
      - internal_nw
    depends_on:
      - broker

    environment:
      DATABASE_URL: postgresql+psycopg://user:password@database:5432/confiacim_api
      CELERY_BROKER_URL: redis://broker:6379
      CELERY_RESULT_BACKEND: redis://broker:6379

  flower:
    image: confiacim_api:latest
    restart: 'no'
    networks:
      - internal_nw
    command: celery --broker=redis://broker:6379/0 flower --port=5555 --url-prefix=flower
    depends_on:
      - broker

volumes:
  pg_data:

networks:
  internal_nw:
    name: "confiacim_internal_nw"
