env:
  AuthorizedGroups: GG_APPS_DEVOPS_ACESSODEV_A17790_K8S
  Name: a17790-backend
  SkipProjectFilesUpdate: true
  SkipSnapshotCommit: true

build:
  python:
    PythonVersion: "3.11"
    SkipTests: true
    SkipSonar: true
  docker:
    Repository: a17790
    Name: backend
    Dockerfile: Dockerfile
    ContextRoot: .
    BuildArgs: IMAGE_REGISTRY=registry.petrobras.com.br/dockerhub/library/

upload:
  docker:

deploy:
  job: a17790-k8s@backend
  # name: a17790-backend
  folder: TIC-US
