class UploadCaseBaseError(Exception): ...


class MaterialsFileNotFoundInZipError(UploadCaseBaseError): ...


class MaterialsFileEmptyError(UploadCaseBaseError): ...


class MaterialsFileValueError(UploadCaseBaseError): ...


class TaskFileCaseNotFound(Exception): ...


class ResultNotFound(Exception): ...
