class MaterialsFileNotFoundInZipError(Exception): ...


class MaterialsFileEmptyError(Exception): ...


class MaterialsFileValueError(Exception): ...


class TaskFileCaseNotFound(Exception): ...


class ResultNotFound(Exception): ...
