class UploadCaseBaseError(Exception): ...


class MaterialsFileNotFoundInZipError(UploadCaseBaseError): ...


class LoadsFileNotFoundInZipError(UploadCaseBaseError): ...


class MaterialsFileEmptyError(UploadCaseBaseError): ...


class LoadsFileEmptyError(UploadCaseBaseError): ...


class hidrationFileEmptyError(UploadCaseBaseError): ...


class MaterialsFileValueError(UploadCaseBaseError): ...


class TaskFileCaseNotFound(Exception): ...


class ResultNotFound(Exception): ...


class InvalidDistNameError(Exception): ...


class CorrelationsInvalidError(Exception): ...
