"""Add variables_stats in FormResult

Revision ID: 097588d1c5ba
Revises: 25b0f40bb3ba
Create Date: 2024-10-07 00:30:08.927368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "097588d1c5ba"
down_revision: Union[str, None] = "25b0f40bb3ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_results", sa.Column("variables_stats", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_results", "variables_stats")
    # ### end Alembic commands ###
