"""Add generated_case_files

Revision ID: 1ab12ae567d7
Revises: 949a58ef46fc
Create Date: 2024-10-26 23:50:07.499154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ab12ae567d7"
down_revision: Union[str, None] = "949a58ef46fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_results", sa.Column("generated_case_files", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_results", "generated_case_files")
    # ### end Alembic commands ###
