"""Change name and type

Revision ID: 374345143513
Revises: 4e4afb61eb68
Create Date: 2024-11-22 21:33:08.516809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "374345143513"
down_revision: Union[str, None] = "4e4afb61eb68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loads_base_case_infos", sa.Column("mechanical_t", postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True)
    )
    op.add_column(
        "loads_base_case_infos", sa.Column("thermal_t", postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True)
    )
    op.drop_column("loads_base_case_infos", "mechanical_istep")
    op.drop_column("loads_base_case_infos", "thermal_istep")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loads_base_case_infos",
        sa.Column("thermal_istep", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    )
    op.add_column(
        "loads_base_case_infos",
        sa.Column("mechanical_istep", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    )
    op.drop_column("loads_base_case_infos", "thermal_t")
    op.drop_column("loads_base_case_infos", "mechanical_t")
    # ### end Alembic commands ###
