"""Add materials model

Revision ID: 553a83605190
Revises: b2aac65bab92
Create Date: 2024-09-08 16:00:37.541653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "553a83605190"
down_revision: Union[str, None] = "b2aac65bab92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials_base_case_average_prop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("E_c", sa.Float(), nullable=False),
        sa.Column("E_f", sa.Float(), nullable=False),
        sa.Column("poisson_c", sa.Float(), nullable=False),
        sa.Column("poisson_f", sa.Float(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("materials_base_case_average_prop")
    # ### end Alembic commands ###
