"""Add the base file.

Revision ID: 7bb0922230d5
Revises: 804fd92d2ad4
Create Date: 2024-07-03 23:09:57.187642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bb0922230d5"
down_revision: Union[str, None] = "804fd92d2ad4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("base_file", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "base_file")
    # ### end Alembic commands ###
