"""Add constrain user-case

Revision ID: 804fd92d2ad4
Revises: 4c4ff3149075
Create Date: 2024-06-29 17:52:40.396505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "804fd92d2ad4"
down_revision: Union[str, None] = "4c4ff3149075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cases_tag_key", "cases", type_="unique")
    op.create_unique_constraint("case_tag_user", "cases", ["tag", "user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("case_tag_user", "cases", type_="unique")
    op.create_unique_constraint("cases_tag_key", "cases", ["tag"])
    # ### end Alembic commands ###
