"""Add rc_limit in TencimResult

Revision ID: a14583722acf
Revises: e9fd6582f431
Create Date: 2024-10-10 23:35:16.657630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a14583722acf"
down_revision: Union[str, None] = "e9fd6582f431"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tencim_results", sa.Column("rc_limit", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tencim_results", "rc_limit")
    # ### end Alembic commands ###
