"""Add description field in Case

Revision ID: b2aac65bab92
Revises: f1232937d0c4
Create Date: 2024-08-18 01:32:09.333544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2aac65bab92"
down_revision: Union[str, None] = "f1232937d0c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "description")
    # ### end Alembic commands ###
