"""Add model LoadsBaseCaseInfo

Revision ID: bf6ce47c0449
Revises: 1ab12ae567d7
Create Date: 2024-11-17 15:03:45.808301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf6ce47c0449"
down_revision: Union[str, None] = "1ab12ae567d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loads_base_case_infos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nodalsource", sa.Float(), nullable=True),
        sa.Column("mechanical_istep", postgresql.ARRAY(sa.Integer(), as_tuple=True), nullable=True),
        sa.Column("mechanical_force", postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True),
        sa.Column("thermal_istep", postgresql.ARRAY(sa.Integer(), as_tuple=True), nullable=True),
        sa.Column("thermal_h", postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True),
        sa.Column("thermal_temperature", postgresql.ARRAY(sa.Float(), as_tuple=True), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("loads_base_case_infos")
    # ### end Alembic commands ###
