"""Add_created_at_and_updated_at

Revision ID: ce65ed45d626
Revises: ff0116c0539e
Create Date: 2024-08-01 20:30:18.600229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce65ed45d626"
down_revision: Union[str, None] = "ff0116c0539e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True))
    op.add_column("cases", sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "updated_at")
    op.drop_column("cases", "created_at")
    # ### end Alembic commands ###
