"""Add description in FormResult and TencimResult

Revision ID: e9fd6582f431
Revises: 097588d1c5ba
Create Date: 2024-10-10 21:51:39.313879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9fd6582f431"
down_revision: Union[str, None] = "097588d1c5ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_results", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("tencim_results", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tencim_results", "description")
    op.drop_column("form_results", "description")
    # ### end Alembic commands ###
