name: "confiacim-api-ci"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest
    env:
      CONFIACIM_API_DB_USER: test_user
      CONFIACIM_API_DB_PASSWORD: test_password
      CONFIACIM_API_DB_HOST: localhost
      CONFIACIM_API_DB_NAME: confiacim_api
      CONFIACIM_API_SENTINEL_MASTER_NAME: mymaster
      CONFIACIM_API_SENTINEL_HOST: sentinel
      CONFIACIM_API_JWT_SECRET_KEY: Chave Secreta JWT
      CONFIACIM_CORE_EXEC_TENCIM_MODE: SEQUENTIAL # TODO: Retirar essa config quando atualiza o core para a versãao 0.13.1

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        python-version: ['3.11']

    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: confiacim_api_test
        ports: [ '5432:5432' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Look for auto format errors (black)
      run:  poetry run black --check --diff confiacim_api/ tests/

    - name: Look for auto format errors (ruff)
      run:  poetry run ruff check confiacim_api/ tests/

    - name: Run mypy
      run:  poetry run mypy --package tests --package confiacim_api

    - name: test
      run: poetry run pytest tests --junitxml=test-result.xml
